version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../babadurusite:/var/storage/www/babadu.ru
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    env_file:
        - ".env"
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - "9191:3306"
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
  php:
    build: .
    volumes: 
      - ../babadurusite:/var/storage/www/babadu.ru
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links: 
      - mysqldb
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8081:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=${MYSQL_HOST}
    depends_on:
        - mysqldb
